In [72]:
#import "../../read_table.py"
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

data = None
data = pd.read_csv("/mnt/lindata/tmp2/TrendAndEnv_eurusd_D1_0.89x1.44.xls", delimiter = "\t")
#data = pd.read_csv("/mnt/lindata/c1.xls", delimiter = "\t")
"""data = pd.read_csv("/mnt/lindata/tmp2/pandas_tutorial_read.csv", 
                   delimiter = ";",
                  names=['my_datetime', 'event', 'country', 'user_id', 'source', 'topic']
)"""
print("read_csv completed")

read_csv completed


In [73]:
print("Количество строк:", len(data))

#print("Уникальных стран:", len(data["country"].unique()))
#unique_countries = data["country"].unique()
#unique_countries.sort()
#print("Список стран:", unique_countries)

data.head(5) # первые 5 строк
#data.tail(5) # последние 5 строк
#data.sample(5) # случайные 5 строк (не обязательно в возрастающем порядке)
#data.info() # количество строк, типы данных для столбцов
#data.describe()

Количество строк: 4398


SN          DateTime   POpen   PHigh    PLow  PClose   PMedian  TrendSign  \
0  855  2007.01.01 00:00  1.3193  1.3220  1.3169  1.3213  1.320200          0   
1  856  2007.01.02 00:00  1.3214  1.3297  1.3196  1.3275  1.324943          0   
2  857  2007.01.03 00:00  1.3273  1.3293  1.3145  1.3171  1.321386         -1   
3  858  2007.01.04 00:00  1.3170  1.3181  1.3075  1.3086  1.312200         -1   
4  859  2007.01.05 00:00  1.3089  1.3106  1.2980  1.3001  1.303814         -1   

   TrendUp  Flat  ...  BackStep#42  BackStep#55  BackStep#68  BackStep#89  \
0        0     1  ...     0.433858     0.481963     0.611879     0.411459   
1        0     1  ...     0.518380     0.553405     0.684197     0.458855   
2        0     0  ...     0.408925     0.429925     0.587864     0.333375   
3        0     0  ...     0.318620     0.322752     0.492251     0.231721   
4        0     0  ...     0.217179     0.232744     0.412916     0.169966   

   BackStep#110  BackStep#144  BackStep#178  BackStep#233  BackStep#288  \
0      0.322772      0.397148      0.224286      0.487492      0.489081   
1      0.364464      0.470609      0.313391      0.485643      0.500648   
2      0.275266      0.385024      0.294863      0.450113      0.467547   
3      0.195273      0.287347      0.257267      0.455590      0.440017   
4      0.118610      0.204537      0.222930      0.433847      0.413448   

   BackStep#377  
0      0.477246  
1      0.502280  
2      0.443180  
3      0.415624  
4      0.401901  

[5 rows x 112 columns]

In [27]:
#data[["country", "user_id"]] # первые и последние 5 строк указанных столбцов


In [74]:
#print(data[["POpen"]])
X = data[["POpen", "PHigh", "PLow"]].to_numpy() # указывать именно две квадратные скобки
Y = data[["PClose"]].to_numpy()
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.67, random_state=42)

In [75]:
print("X:", X)
print("X_train:", X_train)
print("X_test:", X_test)
print ("----------------------")

print("Y:", Y)
print("Y_train:", Y_train)
print("Y_test:", Y_test)


X: [[1.3193  1.322   1.3169 ]
 [1.3214  1.3297  1.3196 ]
 [1.3273  1.3293  1.3145 ]
 ...
 [0.96708 0.97091 0.95491]
 [0.96067 0.96702 0.95684]
 [0.95902 0.95999 0.95352]]
X_train: [[1.11245 1.11633 1.11183]
 [1.4296  1.4452  1.4258 ]
 [1.3141  1.3291  1.3135 ]
 ...
 [1.19182 1.19871 1.19007]
 [1.0979  1.0979  1.08955]
 [1.4593  1.4674  1.4575 ]]
X_test: [[1.2441  1.2692  1.2433 ]
 [1.2918  1.3007  1.2889 ]
 [1.1198  1.1251  1.115  ]
 ...
 [1.1477  1.1485  1.1311 ]
 [1.1019  1.1087  1.096  ]
 [1.14673 1.14895 1.13816]]
----------------------
Y: [[1.3213 ]
 [1.3275 ]
 [1.3171 ]
 ...
 [0.96064]
 [0.95906]
 [0.95513]]
Y_train: [[1.11494]
 [1.4394 ]
 [1.3271 ]
 ...
 [1.19442]
 [1.09031]
 [1.4654 ]]
Y_test: [[1.2666]
 [1.2926]
 [1.1154]
 ...
 [1.1313]
 [1.1041]
 [1.1412]]


In [65]:
# Линейная регрессия
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit(X_train, Y_train)
print(reg.coef_)

[[-0.5222913   0.75269985  0.76967394]]


In [ ]:
data = None